### ISSUE TITLE
Upgrading to Python 3 issue

### ISSUE THREAD

**Issue by ghost** [keenerd/rtl-sdr-misc#28]
Attempting to run in macOS 15 (Sonoma) after converting the script using 2to3, I get the following:

```
x: 129, y: 180, z: (-1.180000, 7.260000)
drawing
labeling
Traceback (most recent call last):
  File "/Users/steven/Downloads/rtl-sdr-misc/heatmap/heatmap.py", line 621, in <module>
    create_labels(args, img)
  File "/Users/steven/Downloads/rtl-sdr-misc/heatmap/heatmap.py", line 569, in create_labels
    tape_text(img, args.freqs, label_base/scale, y-tape_pt)
  File "/Users/steven/Downloads/rtl-sdr-misc/heatmap/heatmap.py", line 534, in tape_text
    w = word_aa(s, tape_pt, 'black', 'yellow')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steven/Downloads/rtl-sdr-misc/heatmap/heatmap.py", line 470, in word_aa
    s = f.getsize(label)
        ^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute ‘getsize'
```

**Comment by Gissio** [comment]
This seems to be the fix: https://github.com/by/rtl-sdr-misc/blob/e322ddec7d1940d226d9f88739ba69225eb9bd33/heatmap/heatmap.py
