### ISSUE TITLE
heatmap compress

### ISSUE THREAD

**Issue by bdn76** [keenerd/rtl-sdr-misc#9]
dima@dima:~$ heatmap --compress 1200 156 156.png
loading
x: 4098, y: 1185, z: (-13.050000, 19.720000)
drawing
Traceback (most recent call last):
  File "/home/dima/bin/heatmap", line 615, in <module>
    img = push_pixels(args)
  File "/home/dima/bin/heatmap", line 422, in push_pixels
    y = args.pix_height - time_compression(height - y, args.compress)
NameError: global name 'height' is not defined
dima@dima:~$ heatmap --compress 0.1 156 156.png
loading
x: 4098, y: 527, z: (-13.050000, 19.720000)
drawing
Traceback (most recent call last):
  File "/home/dima/bin/heatmap", line 615, in <module>
    img = push_pixels(args)
  File "/home/dima/bin/heatmap", line 422, in push_pixels
    y = args.pix_height - time_compression(height - y, args.compress)
NameError: global name 'height' is not defined
dima@dima:~$ 

Compress do not work or i'm doing something wrong?

**Comment by keenerd** [comment]
Looks like I forgot to test a few paths when I was cleaning stuff up.

Does commit ddfe86d work for you?

**Comment by bdn76** [comment]
Work fine. Thank you.
